### ISSUE TITLE
app-misc/mosquitto-1.5: bump version to 1.5

### ISSUE THREAD

**Issue by lramage94** [lramage94/gentoo#8]
Bug: https://bugs.gentoo.org/656572

**Comment by lramage94** [comment]
In Progress https://github.com/lramage94/gentoo/tree/app-misc/mosquitto-1.5

**Comment by lramage94** [comment]
```c
#ifdef WITH_BRIDGE
	char *address;
	int i; // declared here on line 738
#endif
```

**Comment by lramage94** [comment]
https://github.com/eclipse/mosquitto/issues/844
https://github.com/eclipse/mosquitto/pull/810

**Comment by lramage94** [comment]
```patch
diff --git a/src/conf.c b/src/conf.c
index f3d812d..daf2bf4 100644
--- a/src/conf.c
+++ b/src/conf.c
@@ -735,8 +735,8 @@ int config__read_file_core(struct mosquitto__config *config, bool reload, struct
        struct mosquitto__listener *cur_listener = &config->default_listener;
 #ifdef WITH_BRIDGE
        char *address;
-       int i;
 #endif
+       int i;
        int lineno_ext;
        struct mosquitto__security_options *cur_security_options = NULL;

diff --git a/src/net.c b/src/net.c
index 7397de5..670b7e2 100644
--- a/src/net.c
+++ b/src/net.c
@@ -114,7 +114,7 @@ int net__socket_accept(struct mosquitto_db *db, mosq_sock_t listensock)
        fromhost(&wrap_req);
        if(!hosts_access(&wrap_req)){
                /* Access is denied */
-               if(!mosquitto__socket_get_address(new_sock, address, 1024)){
+               if(!net__socket_get_address(new_sock, address, 1024)){
                        log__printf(NULL, MOSQ_LOG_NOTICE, "Client connection from %s denied access by tcpd.", address);
                }
                COMPAT_CLOSE(new_sock);
```

**Comment by lramage94** [comment]
```console
./06-bridge-b2br-remapping.py
1528216562: mosquitto version 1.5 starting
1528216562: Config loaded from 06-bridge-b2br-remapping.conf.
1528216562: Opening ipv4 listen socket on port 1889.
1528216562: Opening ipv6 listen socket on port 1889.
1528216562: Connecting bridge bridge_sample (localhost:1888)
1528216562: Bridge overlay-devel.bridge_sample sending CONNECT
1528216562: Error creating bridge: Connection refused.
1528216562: Warning: Unable to connect to bridge bridge_sample.
1528216562: New connection from ::1 on port 1889.
1528216562: Socket error on client <unknown>, disconnecting.
1528216566: mosquitto version 1.5 terminating

Traceback (most recent call last):
  File "./06-bridge-b2br-remapping.py", line 111, in <module>
    (bridge, address) = ssock.accept()
  File "/usr/lib64/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
socket.timeout: timed out
make[2]: *** [Makefile:83: 06] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-misc/mosquitto-1.5/work/mosquitto-1.5/test/broker'
make[1]: *** [Makefile:15: test] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-misc/mosquitto-1.5/work/mosquitto-1.5/test'
make: *** [Makefile:43: test] Error 2
```
